feat: add covid hospitalizations production pipeline
cmu-delphi/exploration-tooling pull request #113
Opened 2024-04-10 01:03 UTC by dshemetov

Took a while to get the metaprogramming bits right. A few smaller details left:
- [ ] plotting notebook
- [ ] need to double check that we're using the right forecaster with the right params

2024-04-16 19:29 UTC, dsweber2 requested changes
Generally looks good! There's a range of things, but the only hold-ups are the things I actually made suggestions on, and how to handle the exclusion date.

Not sure how seriously to take plotting specific problems, if we're actually just using the results in a different place for now.

2024-04-16 19:29 UTC, dsweber2 commented on scripts/covid_hosp_prod.Rmd
> +exclude_geos <- c("as", "gu", "mp", "vi")
it appears to be excluding the hhs timeseries but not the prediction.

2024-04-16 19:29 UTC, dsweber2 commented on scripts/covid_hosp_prod.Rmd
> +exclude_geos <- c("as", "gu", "mp", "vi")
![image](https://github.com/cmu-delphi/exploration-tooling/assets/7095649/32c11c42-3138-4b2b-aa3b-86a05698adbe)

2024-04-16 19:29 UTC, dsweber2 commented on scripts/plotting.R
> +    time_values = epidatr::epirange("2022-01-01", Sys.Date())
This line means that any plots created after the original forecast date have data from the future. Unsure if feature or bug.
![image](https://github.com/cmu-delphi/exploration-tooling/assets/7095649/e10c6465-f9bf-4784-8321-30159e48330b)

2024-04-16 19:29 UTC, dsweber2 commented on scripts/covid_hosp_prod.Rmd
After running and inspecting, the initial confidence intervals were surprisingly wide from the get-go, but I think that may have been a linreg vs quantreg thing. Currently running with the modification for the speicific `smoothed_scaled` parameters mentioned above.
![image](https://github.com/cmu-delphi/exploration-tooling/assets/7095649/0bbccefa-582c-4b59-84a6-ca411feda821)

2024-04-16 19:29 UTC, dsweber2 commented on scripts/covid_hosp_prod.Rmd
oh also somehow national is hilariously tallllllllllllllll
![image](https://github.com/cmu-delphi/exploration-tooling/assets/7095649/a33bbb68-a44c-4b46-9e25-5146fb3fcbbf)

2024-04-16 19:29 UTC, dsweber2 commented on scripts/covid_hosp_prod.R
> +      c(1:7)
```suggestion
      c(1:28)
```
This should probably be 1:28, right? Guessing this was 1:7 for proof of concept

2024-04-16 19:29 UTC, dsweber2 commented on scripts/geo_exclusions.json
> +        "2024-03-24": "ak,ca"
This is Sunday; I guess it's supposed to indicate the week, rather than the forecast date? Either way, it didn't actually get picked up

2024-04-19 18:37 UTC, dshemetov commented on scripts/covid_hosp_prod.R
> +          smoothed_scaled(outcome = "hhs", ahead = aheads)
That sounds reasonable, I just really don't like the metaprogramming bloat. Just doesn't seem realistic if we plan to give this to a partner and expect them to modify it for their needs. I'd like to find some way to make all that simpler.

2024-04-19 18:42 UTC, dshemetov commented on scripts/plotting.R
Some of it yea, but I also did some clean up in this copy too. Most of it is just simplifying this code and migrating to epidatr.

2024-04-23 00:55 UTC, dshemetov commented on scripts/covid_hosp_prod.R
> +          smoothed_scaled(outcome = "hhs", ahead = aheads)
Trying to do this without passing through the whole "make the function call into a symbol" thing and not having any luck. Maybe I'll have better luck tomorrow.

2024-04-24 00:39 UTC, dsweber2 commented on Makefile
> +pull:
these are basically synonyms, I added multiple so I didn't have to remember which one is actually defined

2024-04-24 00:39 UTC, dsweber2 commented on scripts/covid_hosp_prod.R
> +# forecast_generation_date <- as.character(seq.Date(as.Date("2024-01-01"), Sys.Date(), by = "1 week"))
I guess setting it to 4-22 gives a more realistic picture of when it's starting to run?

2024-04-24 01:43 UTC, dsweber2 approved these changes
should've said approved earlier

2024-04-24 01:43 UTC, merged